### ISSUE TITLE
readme.md typo

### ISSUE THREAD

**Issue by Phoenix1969** [karek314/Lisk-forging-failover#2]
terminating a screen script is Ctrl-C instead of Ctrl-D
![ctld](https://user-images.githubusercontent.com/18568844/45113159-47004700-b0e5-11e8-9677-cd22b69d61be.PNG)

**Comment by karek314** [comment]
Thanks! 
Closed with: https://github.com/karek314/Lisk-forging-failover/commit/4668620fa03bd6bc82341b4d63b2a331c40ccc18
